---
dependencies: []

galaxy_info:
  author: lb2961.ai_driven_aap
  description: Deploy Splunk in a container for log analysis and monitoring
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  
  galaxy_tags:
    - splunk
    - logging
    - monitoring
    - container
    - podman